색상 목록 조회 API 구현 close #13
endless-horses/oot-was pull request #21
Opened 2024-01-19 05:21 UTC by byeon22

## Motivation

메인 페이지, 측면커스텀 페이지, 액세서리 페이지에서 색상 목록 조회 필요

## Problem Solving

색상 목록 조회 API 구현

## To Reviewer

Dto, Repository, Service, Controller 만들어 놓았습니다~!

2024-01-19 05:30 UTC, jinlee1703 requested changes

2024-01-19 05:30 UTC, jinlee1703 commented on src/main/java/com/endlesshorses/oot/custom/color/repository/ColorRepository.java
> +public interface ColorRepository extends JpaRepository<Color, String> {
P1 : `JpaRepository`를 상속받을 때는 `<타입, PK 타입>`을 사용해야 합니다!

2024-01-22 06:10 UTC, SubiHwang approved these changes
확인했습니다!

2024-01-23 05:24 UTC, jinlee1703 approved these changes
확인했습니다~

2024-01-23 05:25 UTC, merged