feat: 패턴 목록 조회 api 구현 #23
endless-horses/oot-was pull request #27
Opened 2024-01-22 12:18 UTC by SubiHwang

## Motivation
패턴 목록 조회 api 구현

## Problem Solving
- controller 생성
- service 생성
- repo 생성
- dto 생성

## To Reviewer

전체적인 흐름에 대한 피드백 부탁드립니다!

2024-01-22 12:54 UTC, jinlee1703 requested changes
전체적으로 브랜치가 좀 꼬인 것 같아요 ㅠㅠ
해결 방법을 찾아봐야 할 것 같습니다.

2024-01-22 12:54 UTC, jinlee1703 commented on src/main/java/com/endlesshorses/oot/custom/pattern/controller/PatternController.java
> +	@RequestMapping("/patterns")
P3: `@RequireMapping` 어노테이션을 클래스에 붙이면 클래스에 통일된 API Path를 설정할 수 있습니다.

2024-01-22 12:54 UTC, jinlee1703 commented on src/main/java/com/endlesshorses/oot/custom/pattern/controller/PatternController.java
> +	public String list(Model model){
P2: Model을 쓰기 보다는 [민정님 PR](https://github.com/endless-horses/oot-was/pull/26)을 참고하면 좋을 것 같아요!

2024-01-22 12:54 UTC, jinlee1703 commented on src/main/java/com/endlesshorses/oot/custom/pattern/repository/PatternRepository.java
> +		return em.createQuery("select p from Pattern p",Pattern.class).getResultList();
P3: JDBC를 사용하기 보다는 `JpaRepository`를 사용해보면 좋을 것 같습니다.

2024-01-23 05:44 UTC, SubiHwang commented on src/main/java/com/endlesshorses/oot/custom/pattern/controller/PatternController.java
> +	@RequestMapping("/patterns")
설정했습니다!

2024-01-23 05:44 UTC, SubiHwang commented on src/main/java/com/endlesshorses/oot/custom/pattern/controller/PatternController.java
> +	public String list(Model model){
네!

2024-01-23 05:44 UTC, SubiHwang commented on src/main/java/com/endlesshorses/oot/custom/pattern/repository/PatternRepository.java
> +		return em.createQuery("select p from Pattern p",Pattern.class).getResultList();
JPA로 코드 변경해두었습니다!

2024-01-23 06:08 UTC, jinlee1703 approved these changes
확인했습니다~~

2024-01-23 06:33 UTC, merged