Result entity 생성 #3
endless-horses/oot-was pull request #8
Opened 2024-01-12 06:37 UTC by SubiHwang

## Motivation

- #3 
- result entity 매핑

## Problem Solving

- result/entity 에서 Result.class 파일에서 매핑

## To Reviewer

- 1:N , N:N 관계 매핑 코드 리뷰 부탁드려요!

2024-01-12 06:48 UTC, jinlee1703 requested changes

2024-01-12 06:48 UTC, jinlee1703 commented on src/main/java/com/endlesshorses/oot/custom/accessory/enity/Accessory.java
> +	@ManyToMany(mappedBy = "accessory")
P3 : many-to-many는 가급적 지양하는 게 좋습니다~

2024-01-12 06:48 UTC, jinlee1703 commented on src/main/java/com/endlesshorses/oot/custom/color/entity/Color.java
> +	@OneToMany(mappedBy = "color")
P1 : `mappedBy`는 Color를 참조하는 테이블의 컬럼명을 써주면 됩니다. ex) `color_id`

2024-01-12 06:48 UTC, jinlee1703 commented on src/main/java/com/endlesshorses/oot/custom/result/entity/Result.java
> +	private Long patterId;
P1 : `@JoinColumn` 어노테이션을 사용할 때 객체 타입은 id의 타입이 아닌, 참조하는 객체의 타입으로 하면 됩니다. ex) `Pattern pattern`

2024-01-14 04:54 UTC, byeon22 approved these changes
좋습니다!

2024-01-14 05:05 UTC, jinlee1703 approved these changes
확인했습니다!

2024-01-14 05:29 UTC, jinlee1703 approved these changes
확인했습니다!

2024-01-14 05:29 UTC, jinlee1703 commented on src/main/java/com/endlesshorses/oot/custom/resultAccessory/entity/ResultAccessory.java
> +public class ResultAccessory {
<img width="635" alt="image" src="https://github.com/endless-horses/oot-was/assets/68031450/c397c7e4-5c27-49e1-9166-4824e919bb11">

P4: 테이블명을 조금 더 고민해보시면 좋을 것 같아요!

2024-01-14 05:29 UTC, merged